_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True  True  True  True  True  True  True]'
_last_obs:
    value: |-
        [[ 1.36681175e+00  1.42369354e+00  2.23797187e-01  7.79684586e-03]
         [ 1.54536366e-01 -4.18006033e-01  9.04911533e-02 -7.23470569e-01]
         [ 7.57932484e-01  1.44641328e+00  2.61530429e-01 -3.72796282e-02]
         [ 4.96402055e-01  1.48369300e+00 -2.61530429e-01  3.72796282e-02]
         [ 1.14301455e+00  1.41589677e+00 -2.23797187e-01 -7.79684586e-03]
         [ 1.28833580e+00  1.11559010e+00 -7.84759074e-02 -3.08103532e-01]
         [ 6.40452057e-02  3.05464536e-01 -3.88562754e-02 -2.30051875e-01]
         [ 1.02901481e-01  5.35516381e-01  3.88562754e-02  2.30051875e-01]
         [-4.10586089e-01  1.48476958e+00 -9.06988144e-01  1.07667083e-03]
         [-4.96965885e-01  4.12761599e-01 -5.61011076e-01  1.07297085e-01]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7f5edb67fe60>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 50000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 2
                - 3
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.12.7
            "5": 0.19.1
            "8":
                - 5
                - 13
            "12": 0.19.1
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Discrete(5)
algo:
    value: PPO
algorithm:
    value: PPO
batch_size:
    value: 256
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x7f5ea3dda7a0>
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.vec_monitor.VecMonitor object at 0x7f5f6cce7050>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
iterations:
    value: 10
learning_rate:
    value: 0.0003
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x7f5f6c708c20>
max_cycles:
    value: 1000
max_grad_norm:
    value: 0.5
n_envs:
    value: 10
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_agents:
    value: 10
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (4,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=4, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=4, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=5, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f5f91c1df70>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1735056475323660540
target_kl:
    value: None
tensorboard_log:
    value: /home/peas/Documents/Collective Intelligence/formation-tim/logs/tensorboard
total_timesteps:
    value: 50000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
