# configs/env/formation.yaml
name: "FormationEnv"
num_agents: 5
arena_size: 3.0 # Ensure this is large enough for your circle + movement
max_steps: 200 # Or more for learning complex tasks

shape_type: "circle"

circle:
  center: [0.0, 0.0]
  radius: 0.8 # Agents try to be at this distance

# ... (curvilinear_triangle params can remain for future use) ...

agent_size: 0.05 # Diameter of agent in world units
agent_accel: 3.0
agent_max_speed: 0.5 # Increased slightly
# dt: 0.1

obs_keys_for_actor: ["observation"]