_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True  True  True  True  True  True  True]'
_last_obs:
    value: |-
        [[ 0.6874115   0.94990456  0.17430921 -0.0776358 ]
         [ 0.29375985 -0.3298744   0.5150449   0.0783736 ]
         [ 0.59462124  1.1758416   0.08151893  0.14830118]
         [-0.22128509 -0.40824798 -0.5150449  -0.0783736 ]
         [ 1.3238918   0.9744824   0.6364802   0.02457785]
         [ 0.7690944   0.03983307  0.3442705  -0.21002325]
         [ 0.42482394  0.24985632 -0.3442705   0.21002325]
         [ 0.5131023   1.0275404  -0.08151893 -0.14830118]
         [ 1.2412078   0.23851551  0.47211343  0.19868243]
         [-0.47040215  0.995166   -0.9835045  -0.03237439]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7fdf1cef1b20>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 50000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 3
                - 16
                - 22
                - 23
                - 24
                - 34
                - 35
                - 55
            "4": 3.12.7
            "5": 0.19.1
            "8":
                - 5
                - 13
            "12": 0.19.1
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Discrete(5)
algo:
    value: PPO
algorithm:
    value: PPO
batch_size:
    value: 256
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x7fdf1cec9260>
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.vec_monitor.VecMonitor object at 0x7fdfeff62570>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
iterations:
    value: 10
learning_rate:
    value: 0.0003
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x7fdfeff5ed40>
max_cycles:
    value: 1000
max_grad_norm:
    value: 0.5
n_envs:
    value: 10
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_agents:
    value: 10
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (4,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=4, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=4, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=5, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7fdfeff62900>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1735056009296400927
target_kl:
    value: None
tensorboard_log:
    value: /home/peas/Documents/Collective Intelligence/formation-tim/logs/tensorboard
total_timesteps:
    value: 50000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
